# Tutorial 1: Ring Tensor
In MPCTensorLib, the basic data structure is ```RingTensor```, which means the tensor on the ring, corresponding to the tensor of ```torch```. We transform the tensor of ```torch``` to the ```RingTensor``` and perform operations on it, which supports multiple data types of ```torch``` (int64, int32, float64, float32).
Now let's start by importing the RingTensor package.

In [1]:
from common.tensor import RingTensor
import torch

### Conversion between torch tensors and RingTensor
The lib provides a ``convert_to_ring`` method to convert a tensor from ``torch.Tensor`` to ``RingTensor``. The ```convert_to_real_field`` method converts a ``RingTensor`` data to a ``torch.Tensor`` type.

In [2]:
# Create torch tensor
x = torch.tensor([1.0, 2.0, 3.0])

# Convert a tensor to ring
x_on_ring = RingTensor.convert_to_ring(x)
print(x_on_ring)

# Convert a RingTensor to real field
x_real_field = x_on_ring.convert_to_real_field()
print(x_real_field)

RingTensor
 value:tensor([ 65536, 131072, 196608]) 
 dtype:float 
 scale:65536
tensor([1., 2., 3.])


This lib supports the ` ` ` torch.int64 ` ` ` , ` ` ` torch.int32 ` ` ` , ` ` ` torch.float64 ` ` ` and ` ` ` torch.float32 ` ` ` type of data conversion to the ring.

In [3]:
# Convert different data type tensor to ring
# torch.int64
x_int64 = torch.tensor([1, 2, 3], dtype=torch.int64)

x_int64_on_ring = RingTensor.convert_to_ring(x_int64)
print(x_int64_on_ring)

# torch.int32
x_int32 = torch.tensor([1, 2, 3], dtype=torch.int32)

x_int32_on_ring = RingTensor.convert_to_ring(x_int32)
print(x_int32_on_ring)

# torch.float64
x_float64 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

x_float64_on_ring = RingTensor.convert_to_ring(x_float64)
print(x_float64_on_ring)

# torch.float32
x_float32 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

x_float32_on_ring = RingTensor.convert_to_ring(x_float32)
print(x_float32_on_ring)

RingTensor
 value:tensor([1, 2, 3]) 
 dtype:int 
 scale:1
RingTensor
 value:tensor([1, 2, 3]) 
 dtype:int 
 scale:1
RingTensor
 value:tensor([ 65536, 131072, 196608]) 
 dtype:float 
 scale:65536
RingTensor
 value:tensor([ 65536, 131072, 196608]) 
 dtype:float 
 scale:65536


## Operations on Ring tensor
Now let's look at what we can do with our ```RingTensor```

#### Arithmetic Operations
We can carry out regular arithmetic operations between ```RingTensors```. These operations return a ring tensor output.

In [4]:
# Arithmetic operations between RingTensors
x_on_ring = RingTensor.convert_to_ring(torch.tensor([1.0, 2.0, 3.0]))

y_on_ring = RingTensor.convert_to_ring(torch.tensor([2.0]))


# Addition
res_on_ring = x_on_ring + y_on_ring
print("\nAddition:", res_on_ring.convert_to_real_field())

# Subtraction
res_on_ring = x_on_ring - y_on_ring
print("\nSubtraction", res_on_ring.convert_to_real_field())

# Multiplication
res_on_ring = x_on_ring * y_on_ring
print("\nMultiplication", res_on_ring.convert_to_real_field())

# Matrix Multiplication
y_on_ring = RingTensor.convert_to_ring(torch.tensor([[1.0], [2.0], [3.0]]))
res_on_ring = x_on_ring @ y_on_ring
print("\nMatrix Multiplication", res_on_ring.convert_to_real_field())


Addition: tensor([3., 4., 5.])

Subtraction tensor([-1.,  0.,  1.])

Multiplication tensor([2., 4., 6.])

Matrix Multiplication tensor([14.])


#### Comparisons
Similarly, we can compute element-wise comparisons on ```RingTensors```. Different from arithmetic operations, comparisons performed on ```RingTensors``` will return ```True``` or ```False```, which is like comparisons between ```torch``` tensors.

In [5]:
#Comparisons between RingTensors
x_on_ring = RingTensor.convert_to_ring(torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0]))

y_on_ring = RingTensor.convert_to_ring(torch.tensor([5.0, 4.0, 3.0, 2.0, 1.0]))

# Less than
result = x_on_ring < y_on_ring
print("\n(x < y) :", result)

# Less than or equal
result = x_on_ring <= y_on_ring
print("\n(x <= y) :", result)

# Greater than
result = x_on_ring > y_on_ring
print("\n(x > y) :", result)

# Greater than or equal
result = x_on_ring >= y_on_ring
print("\n(x >= y) :", result)

# Equal
result = x_on_ring == y_on_ring
print("\n(x == y) :", result)

# Not Equal
result = x_on_ring != y_on_ring
print("\n(x != y) :", result)


(x < y) : RingTensor
 value:tensor([ True,  True, False, False, False]) 
 dtype:float 
 scale:65536

(x <= y) : RingTensor
 value:tensor([ True,  True,  True, False, False]) 
 dtype:float 
 scale:65536

(x > y) : RingTensor
 value:tensor([False, False, False,  True,  True]) 
 dtype:float 
 scale:65536

(x >= y) : RingTensor
 value:tensor([False, False,  True,  True,  True]) 
 dtype:float 
 scale:65536

(x == y) : RingTensor
 value:tensor([False, False,  True, False, False]) 
 dtype:float 
 scale:65536

(x != y) : RingTensor
 value:tensor([ True,  True, False,  True,  True]) 
 dtype:float 
 scale:65536


#### Other operations
The library also supports some other operations on RingTensor, such as reshape, stack, cat, unsqueeze and so on.


In [6]:
x_on_ring = RingTensor.convert_to_ring(torch.tensor([1.0, 2.0, 3.0]))
y_on_ring = RingTensor.convert_to_ring(torch.tensor([4.0, 5.0, 6.0]))

# Concatenation
res_on_ring = RingTensor.cat((x_on_ring, y_on_ring))
print("Concatenation: \n", res_on_ring.convert_to_real_field())

# Stacking
res_on_ring = RingTensor.stack((x_on_ring, y_on_ring))
print("\nConcatenation: \n", res_on_ring.convert_to_real_field())

# Reshaping
res_on_ring_after_reshape = res_on_ring.reshape(-1, 6)
print("\nReshape: \n", res_on_ring_after_reshape.convert_to_real_field())

# UnSqueezing
res_on_ring = x_on_ring.unsqueeze(dim=1)
print("\nUnSqueezing: \n", res_on_ring.convert_to_real_field())

Concatenation: 
 tensor([1., 2., 3., 4., 5., 6.], device='cuda:0')

Concatenation: 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

Reshape: 
 tensor([[1., 2., 3., 4., 5., 6.]])

UnSqueezing: 
 tensor([[1.],
        [2.],
        [3.]])


Some functions like where, random, arange is also supported in the RingTensor, but the usage is a little different from above. We need import another package `RingFunc` to use these functions.

In [7]:
from common.tensor import RingFunc

# Where
x_on_ring = RingTensor.convert_to_ring(torch.tensor([1.0, 5.0, 3.0]))
y_on_ring = RingTensor.convert_to_ring(torch.tensor([4.0, 2.0, 6.0]))
condition = x_on_ring > y_on_ring

res_on_ring = RingFunc.where(condition, x_on_ring, y_on_ring)
print("\nWhere: \n", res_on_ring.convert_to_real_field())

# Random
res_on_ring = RingFunc.random(shape=(2, 3), dtype='int', device='cpu', down_bound=0, upper_bound=10)
print("\nRandom: \n", res_on_ring.convert_to_real_field())

# Arange
res_on_ring = RingFunc.arange(start=0, end=10, step=2, dtype='int', device='cpu')
print("\nArange: \n", res_on_ring.convert_to_real_field())


Where: 
 tensor([4., 5., 6.])

Random: 
 tensor([[9., 7., 6.],
        [2., 3., 7.]])

Arange: 
 tensor([0., 2., 4., 6., 8.], device='cuda:0')


There are some other functions in the RingFunc, you can find them in the `common/tensor/functional.py` file. Note that the condition of the where function must be a RingTensor, and the rest of the arguments can be RingTensor or int.